name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        description: Publish on npm
        required: false
        default: false
        type: boolean
      deploy:
        description: Deploy website
        required: false
        default: true
        type: boolean
  release:
    types: [published]

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Publish: ${{ github.event.inputs.publish }}"
          echo "Deploy:  ${{ github.event.inputs.deploy }}"

  package:
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      publish: ${{ github.event_name == 'release' || github.event.inputs.publish }}

  website:
    uses: ./.github/workflows/website.yml
    secrets: inherit
    with:
      deploy: ${{ github.event_name == 'release' || github.event.inputs.deploy }}
