# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run typecheck (react-day-picker)
        run: yarn workspace react-day-picker run typecheck
      - name: Run lint (react-day-picker)
        run: yarn workspace react-day-picker run lint --max-warnings 0
      - name: Run test (react-day-picker)
        run: yarn workspace react-day-picker run test
      - name: Run typecheck (website)
        run: yarn workspace website run typecheck
      - name: Run lint (website)
        run: yarn workspace website run lint --max-warnings 0
      - name: Run test (website)
        run: yarn workspace react-day-picker run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build (react-day-picker)
        run: yarn workspace react-day-picker run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: packages/react-day-picker/dist

  publish-npm:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
