name: "Publish react-day-picker"

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Get version name
        id: get-tag-name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-tag-name.outputs.VERSION }}

      - name: Run build (react-day-picker)
        run: |
          yarn workspace react-day-picker run build

      - name: Publish on npm
        run: npm publish
        working-directory: ./packages/react-day-picker
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-website:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: |
          yarn install --immutable
          yarn add react-day-picker@latest
      - name: Build website
        run: |
          yarn workspace website build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
