name: "react-day-picker"

on:
  pull_request:
    branches:
      - master
    paths:
      - "packages/**"
  push:
    branches:
      - master
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Run typecheck (workspaces)
        run: |
          yarn workspaces foreach run typecheck
      - name: Run lint (workspaces)
        run: |
          yarn workspaces foreach run lint --max-warnings 0
      - name: Run test (workspaces)
        run: |
          yarn workspaces foreach run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Run build (workspaces)
        run: |
          yarn workspaces foreach run build
