name: "CI: website-deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "!packages/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run typecheck (website)
        run: |
          yarn workspace website run typecheck
      - name: Run linter (website)
        run: |
          yarn workspace website run lint --max-warnings 0
      - name: Run tests (website)
        run: |
          yarn workspace website run test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy website
        run: |
          yarn workspace website run deploy
