name: Deploy website

on:
  push:
    paths:
      - "website/**"
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn workspace react-day-picker run build
      - uses: actions/upload-artifact@v3
        with:
          name: rdp-dist
          path: packages/react-day-picker/dist

  test:
    runs-on: ubuntu-latest
    needs: [build-package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: actions/download-artifact@v3
        with:
          name: rdp-dist
          path: packages/react-day-picker/dist
      - run: yarn install --frozen-lockfile
      - run: yarn workspace website run typecheck
      - run: yarn workspace website run lint
      - run: yarn workspace website run test

  build:
    runs-on: ubuntu-latest
    needs: [build-package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: actions/download-artifact@v3
        with:
          name: rdp-dist
          path: packages/react-day-picker/dist
      - run: yarn install --frozen-lockfile
      - run: yarn workspace website build
      - uses: actions/upload-artifact@v3
        with:
          name: website-build
          path: website/build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: actions/download-artifact@v3
        with:
          name: website-build
          path: website/build
      - run: yarn install --frozen-lockfile
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
